language: java
sudo: required

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: osx
      env: OSX=10.12.1
      osx_image: xcode8.2

script:
  - uname -a

  - chmod +x ./gradlew
  - ./gradlew clean build

